watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "home",
        "glazewm_workspaces",
        "active_window",
      ]
      center: []
      right: [
        "glazewm_tiling_direction",
        "cpu",
        "memory",
        "battery",
        "volume",
        "clock",
      ]
widgets:
  # Left
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_list:
        - { title: "  Home", path: "~" }
        - { title: "  Download", path: "~\\Downloads" }
        - { title: "󰧮  Documents", path: "~\\Documents" }
        - { title: "  Pictures", path: "~\\Pictures" }
      menu_labels: {
        'shutdown': '󰐥  Shutdown',
        'restart': '  Restart',
        'logout': '󰍃  Logout',
        'lock': '  Lock',
        'sleep': '󰒲  Sleep',
        'system': '  System Settings',
        'about': '  About This PC',
        'task_manager': '󰕮  Task Manager'
      }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      container_padding: 
        top: 0
        left: 4
        bottom: 0
        right: 4
      alignment: "left"
      direction: "down"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 60
      max_length_ellipsis: "..."
      monitor_exclusive: false
  # Right
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span></span> {info[percent][total]}%"
      update_interval: 1500
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span></span> {virtual_mem_percent}%"
      update_interval: 1500
      memory_thresholds:
        low: 30
        medium: 50
        high: 80
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons: {
        icon_charging: '󰂄',
        icon_critical: '󰁺',
        icon_low: '󰁼',
        icon_medium: '󰁾',
        icon_high: '󰂀', 
        icon_full: '󰁹'
      }
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - ""
        - ""
        - ""
        - ""
        - ""
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>󰃰</span> {%Y-%m-%d %H:%M}"
